version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.0

parameters:
  build-docs:
    type: boolean
    default: false
    description: "Build documentation if true"
  from-setup:
    type: boolean
    default: true
    description: "Dummy pipeline param from this setup config"

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            docs/.* build-docs true
