version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.0

parameters:
  build-docs:
    type: boolean
    default: false
    description: "Build documentation if true"

jobs:
  echo:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Greet
          command: echo "I love ${COLOR} builds."
          environment:
            COLOR: "green"

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            docs/.* build-docs true
